version: 2.1

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-to-pypi:
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/  


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: build
          command: |
            sudo apt-get update -y
            sudo apt-get install cmake -y 
            pip install -e .
  
  deploy-to-pypi:
    docker:
      - image: cimg/python:3.7
    resource_class: small
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $pu" >> ~/.pypirc
            echo -e "password = $pp" >> ~/.pypirc
      - run: 
          name: create package
          command: |
            pip install wheel twine
            python setup.py sdist bdist_wheel
      - run: 
          name: upload
          command: twine upload dist/*



