version: 2.1

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-to-pypi:
          filters:
            tags:
              only: /.*/
          requires:
            - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python3.6
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: build
          command: pip install -e .
  
  deploy-to-pypi:
    docker:
      - image: cimg/python3.6
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $pu" >> ~/.pypirc
            echo -e "password = $pp" >> ~/.pypirc
      - run: 
          name: create package
          command: |
            pip install wheel twine
            python setup.py sdist bdist_wheel
      - run: 
          name: upload
          command: twine upload dist/*



